version: '3.8'

services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql_python
    ports: 
      - 3306:3306
    environment:
      MYSQL_USER: api-accounts
      MYSQL_PASSWORD: accounts
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account-management
    networks:
      - database_net

  grafana:
    image: grafana/grafana:8.4.3
    container_name: grafana_python
    depends_on:
        - prometheus
    environment:
        GF_USERS_ALLOW_SIGN_UP: "false"
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
        - ./etc/grafana/provisioning:/etc/grafana/provisioning
        - ./etc/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    networks:
      - monitor_net

  prometheus:
    image: prom/prometheus:v2.8.1
    container_name: prometheus_python
    volumes:
        - ./etc/prometheus/:/etc/prometheus/
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
        - '--storage.tsdb.retention=200h'
        - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitor_net

networks:
  database_net:
    driver: bridge
  monitor_net:
    driver: bridge